bazelbuild/remote-apis-sdks

go/client/bytestream.go
go/client/cas.go
go/client/client.go
go/client/exec.go

Verified that the following makes no changes / requires no changes:
```
go mod tidy
gofmt -w go
golint ./...
go vet ./...
```
Tested successfully with:
```
bazel test ...
go test ./...
```

Refactor to expose some Client fields for extensions.

---

BUILD.bazel
WORKSPACE
remote-apis-sdks-deps.bzl

This can be used by repos depending on this to load the necessary dependencies instead of having to copy them over manually.

Add a starlark deps function. 

---

go/pkg/moreflag/BUILD.bazel
go/pkg/moreflag/moreflag.go
go/pkg/moreflag/moreflag_test.go

The code for StringMapValue is stolen from re-client repo, the code for StringListValue is stolen from internal flag package (but I'm pretty sure will be open sourced in the next Go version).

Adding moreflag package for two advanced flag types.

---

go/client/tree.go
go/client/tree_test.go
go/internal/test/fakes/ac.go
go/pkg/command/command.go

This doesn't handle the executable bit correctly, but then nothing else in the current client does. It's an upstream bug that I will fix separately, for now the unit tests do not include the executable bit case.

 Adding capability to handle virtual inputs.

---

go/pkg/command/BUILD.bazel
go/pkg/command/command.go
go/pkg/command/command_test.go
go/pkg/fakes/BUILD.bazel
go/pkg/fakes/server.go
go/pkg/rexec/BUILD.bazel
go/pkg/rexec/rexec.go
go/pkg/rexec/rexec_test.go

Refactoring the current rexec_test to use it. Note that tests have not
been removed! They just became more easily packaged into test structs
using the new fake.

Exporting fakes.NewTestEnv.

---

go/client/bytestream.go
go/client/cas.go
go/client/client.go
go/pkg/rexec/rexec.go
go/pkg/tree/BUILD.bazel
go/pkg/tree/tree.go
go/pkg/tree/tree_test.go

Forking client/tree into a separate package. For the time being, keeping the old code as well, will remove it once all existing users are migrated.
Coverting rexec to use the new package along with the new UploadIfMissing, completing the fix of #32.
Tested manually on a command with 400000 input files.

Building Merkle tree into Chunkers

---

go/pkg/rexec/BUILD.bazel
go/pkg/rexec/rexec.go

Interfaces should be defined where they are used; but rexec doesn't actually *use* the FileMetadataCache, it just passes it on to the tree package which actually uses it.
Having the interface defined in rexec adds another place that we would have to fix when the interface changes.

Removing duplicated interface definition

---

go/pkg/rexec/rexec.go
go/pkg/rexec/rexec_test.go

Introducing the rexec.ExecutionContext, to allow calling more intermediate functions. Part 1 of #58.

 Refactoring in preparation for updating remote cache

---

go/pkg/filemetadata/filemetadata.go
go/pkg/filemetadata/filemetadata_test.go
go/pkg/tree/tree.go
go/pkg/tree/tree_test.go

This change facilitates caching of filemetadata query errors.

 Embed error in filemetadata Metadata struct instead of returning the error explicitly.

---

WORKSPACE

In another project (https://github.com/buchgr/bazel-remote/pull/97)
I noticed a mac build error in buildkite with the previous configuration
claiming that repository_rules.bzl needed a matching BUILD file.
Updating to the tip of master helped- I suspect due to
https://github.com/bazelbuild/remote-apis/pull/83

avoid mac build error because repository_rules.bzl needs a BUILD file

---

check-gofmt.sh

misc/git/pre-commit was removed from the go repository by this CL:
https://go-review.googlesource.com/c/go/+/158677
This new link here was the last version of the file before it was removed,
and is unlikely to break again anytime soon.

fix broken link in check-gofmt.sh

---

go/client/client.go

This is intended for derived clients that provide extra services.
Allows to unblock internal refactoring for #78.

Exporting the gRPC connection.

---

go/client/client.go
go/flags/flags.go

Prepares for addition of a second connection to the CAS service in
DialParams (#78). Also adding better named overloads for constructors in
order to migrate users to these names.

Hiding public constructors that take a gRPC connection.

---

go/client/BUILD.bazel
go/client/batch_retries_test.go
go/client/exec.go
go/pkg/command/BUILD.bazel
go/pkg/command/command_test.go
go/pkg/rexec/BUILD.bazel
go/pkg/rexec/rexec_test.go

Closes #93. Generated protobuf messages contain internal data structures
that general purpose comparison functions (e.g., reflect.DeepEqual,
pretty.Compare, etc) do not properly compare. It is already the case
today that these functions may report a difference when two messages
are actually semantically equivalent.
Fix all usages by either calling proto.Equal directly if
the top-level types are themselves proto.Message, or by calling
cmp.Equal with the cmp.Comparer(proto.Equal) option specified.
This option teaches cmp to use proto.Equal anytime it encounters
proto.Message types.

Fix generic comparisons on protobuf messages

---

go/pkg/client/client.go

As stated in the [design doc](https://docs.google.com/document/d/1AaGk7fOPByEvpAbqeXIyE8HX_A3_axxNnvroblTZ_6s/edit#heading=h.7ayoyyemcljy) `instance name` should be allowed to be empty.
Log a warning instead of failing, when the instance name is empty.

Warn on empty instance name instead of failing.

---

go/pkg/client/client.go

Pretty simple one; our use case is wanting to apply some custom interceptors (for metrics / stats etc).

Allow the user to specify additional DialOpts

---

go/pkg/client/cas.go
go/pkg/client/cas_test.go

Pairs with WriteProto; seems pretty generally useful. It's not hard to roll oneself but nice to provide it here I think.

Add a ReadProto function to Client 

---

go/pkg/client/client.go

If you configure the Client with a different CAS endpoint to the execution endpoint, it only returns capabilities from the latter; if that is execution-only then the caller has no direct means of getting the CacheCapabilities without calling themselves.
I'm unsure if this is the "right" way to handle this issue in this SDK; maybe it should be a different function, and there's an awkward fringe case where the execution server returns CacheCapabilities as well (I think this is still the right thing though since the CAS server is the one that actually gets used).

Multiplex remote capabilities between execution / CAS

---

.bazelci/presubmit.yml

This was made the default in https://github.com/bazelbuild/continuous-integration/pull/957.

Remove explicit "set -e" from presubmit.yml

---

go/cmd/rexec/main.go
go/pkg/cache/BUILD.bazel
go/pkg/cache/cache.go
go/pkg/cache/cache_test.go
go/pkg/cache/singleflightcache/BUILD.bazel
go/pkg/cache/singleflightcache/singleflightcache.go
go/pkg/cache/singleflightcache/singleflightcache_test.go
go/pkg/fakes/server.go
go/pkg/filemetadata/BUILD.bazel
go/pkg/filemetadata/cache.go
go/pkg/filemetadata/cache_test.go
go/pkg/filemetadata/filemetadata.go
go/pkg/rexec/BUILD.bazel
go/pkg/rexec/rexec.go
go/pkg/tree/tree.go
go/pkg/tree/tree_test.go

Some refactoring of our previous code, including:
- the interface is now defined in filemetadata.Cache
- the actual types are not exported.
- instead, factory functions are used for both the noop cache
and the single-flight cache

Adding in-memory filemetadata cache.

---

go/pkg/filemetadata/filemetadata.go
go/pkg/tree/tree.go
go/pkg/tree/tree_test.go

When given an output directory containing an invalid symlink (i.e., a
symlink pointing to a non-existent file), the SDK fails to compute
Merkle tree because of Stat failure. This change makes the SDK ignore
it.
Tested by both using this version of re-client and added unit-tests.

Ignore invalid symlinks when computing Merkle tree

---

go.sum
go/pkg/filemetadata/cache.go
go/pkg/filemetadata/cache_posix_test.go
go/pkg/filemetadata/cache_test.go
go/pkg/filemetadata/filemetadata.go
go/pkg/filemetadata/filemetadata_test.go

Since we are not using the mtime based validating cache anywhere and
dont have immediate plans of using it due to performance reasons, I'm
removing this code. This would make it a little bit simpler to update
the cache entry of the output files.
Test: Unit tests

Remove Validating cache

---

go.sum
go/pkg/cache/cache.go
go/pkg/cache/singleflightcache/singleflightcache.go
go/pkg/cache/singleflightcache/singleflightcache_test.go
go/pkg/client/BUILD.bazel
go/pkg/client/cas.go
go/pkg/client/cas_test.go
go/pkg/filemetadata/cache.go
go/pkg/filemetadata/filemetadata.go
go/pkg/rexec/rexec.go
go/pkg/tree/tree_test.go

When we download files as part of action result, we also want to update
the digest of the downlaoded file into the file metadata cache so that:
1. Actions that have inputs as outputs reflect the updated digest of the
output
2. We don't have to recompute the digest of outputs if its already
present in the cache and the outputs are used as inputs to another
action
Test:
1. Updated existing unit-test to verify that digest is set in cache
2. Tested the change by integrating it with reproxy:
Ran this command with/ without this change:
FLAG_platform="container-image=docker://gcr.io/androidbuild-re-dockerimage/android-build-remoteexec-image@sha256:582efb38f0c229ea39952fff9e132ccbe183e14869b39888010dacf56b360d62,jdk-version=10" FLAG_exec_strategy=remote …

Update cache entries of output files

---

go/pkg/tree/tree.go
go/pkg/tree/tree_test.go

This is to make GetTree to CAS work for root directory digest when
we upload all chunkers returned from ComputeOutputsToUpload.

return digest of root directory from ComputeOutputsToUpload

---

go/pkg/tree/tree.go
go/pkg/tree/tree_test.go

This one bit us because we were flattening the tree and then attempting to find any missing blobs. Our CAS proxy was then blowing up because it couldn't discern the correct replica from the hash. 
I think this behavior is more inline with what `tree.ComputeOutputsToUpload` does. Perhaps we should do something similar with symlinks?

Set the empty digest for empty directories when flattening a tree

---

go/pkg/client/cas.go
go/pkg/client/cas_test.go

I'd like to use this function from our client implementation tracked in https://crbug.com/1110569
We will use local disk cache for blobs in our client, but existing functions in this SDK don't allow to integrate our cache implementation easily.

client: make DownloadFiles public

---

go.sum
go/pkg/client/cas.go
go/pkg/client/cas_test.go
go/pkg/command/command.go
go/pkg/rexec/rexec.go
go/pkg/rexec/rexec_test.go

Adding this stats so that we don't have to repeat ourselves on the Swarming side. Is there any concerns that changing the method signature could break the clients?

Add UploadIfMissingStats to report the CAS misses

---

go.sum
go/cmd/remotetool/BUILD.bazel
go/cmd/remotetool/main.go
go/pkg/client/BUILD.bazel
go/pkg/tool/BUILD.bazel
go/pkg/tool/tool.go
go/pkg/tool/tool_test.go

More often we find ourselves wanting to download the results of an
action digest to see what they were. This tool lets us do that. Pass it
an action digest and it would download the results to the given
directory.
Test:
1. Ran against a test RBE stack and it downloaded the RBE action output
2. Unit tests

Tool to download results of a given action digest

---

go/pkg/rexec/rexec.go
go/pkg/rexec/rexec_test.go

DownloadResults will download the results of the action in the
execution context, regardless of the DownloadOutputs option set in
the context.
Test: unit tests

Add DownloadResults function to download the results of an action.

---

go/api/command/BUILD.bazel
go/cmd/remotetool/main.go
go/pkg/fakes/cas.go
go/pkg/fakes/server.go
go/pkg/tool/BUILD.bazel
go/pkg/tool/tool.go
go/pkg/tool/tool_test.go

The tool traverses both input and output directories recursively and
shows:
1. Empty directories
2. Files
3. Symlinks
The previous tool based on tools_remote only used to show the top level
output directories and didn't support symlinks.
As part of this change, I also:
1. Added fake GetTree() function (this was also a feature reequest from
the Goma team).
2. Added support for fake inputs in SDK.
3. Rearranged some of the fake server setup code so that options are
applied first before Merkle tree is computed. I'm doing this since fake
inputs need to be created from the options before Merkle tree is
computed.
Test: Unit-tests, variety of inteegration tests against actual action
digests in test stack.

Tool to show inputs/outputs & command of an action

---

go/pkg/client/cas.go
go/pkg/client/cas_test.go

This improves time of DownloadFiles in n1-standard-8 Windows GCE with standard disk when downloading 14k+ files from 125s to 75s (14s to 11s in one time measure on Linux).

cas: utilize locality when writing files to disk in DownloadFiles

---

go/pkg/balancer/gcp_balancer.go
go/pkg/client/cas_test.go
go/pkg/client/client.go
go/pkg/fakes/server.go
go/pkg/flags/BUILD.bazel
go/pkg/flags/flags.go

Also changed the default values of these parameters to reflect our
experiments with them from asia region.
1. We need to be able to do more than 50 concurrent CAS RPCs if we are
running a build at 500 parallelism for example.
2. In long-haul links like from asia-east <-> us-central, fewer stream
RPCs per connection is better than more stream RPCs per stream. Even at
50 stream RPCs per conn, we see a 3x latecy increase.

Make max concurrent requests and streams as flags

---

README.md

I took this from
https://pkg.go.dev/badge/?path=https%3A%2F%2Fpkg.go.dev%2Fmod%2Fgithub.com%2Fbazelbuild%2Fremote-apis-sdks

add link to godev

---

go/pkg/cache/singleflightcache/singleflightcache_test.go

There's a race condition where we might sometimes delete a value after
Store() and before LoadOrStore(), so the test fails flakily. Making them
mutually exclusive so they don't fail anymore.
Test: bazelisk test --runs_per_test 200 --features race  //go/pkg/cache/singleflightcache:go_default_test --test_output=streamed --test_filter="TestStore" (this failed 4/200 without the fix and 0/400 with the fix).

Make Store() and Delete() mutually exclusive

---

go/pkg/client/cas.go
go/pkg/client/cas_test.go

Reverts bazelbuild/remote-apis-sdks#164
This might cause download latency in Android. We need more recent changes than this for our next release, so reverting it now and fixing it later.

Revert "cas: utilize locality when writing files to disk in DownloadFiles"

---

go/pkg/client/cas.go
go/pkg/client/cas_test.go

I'd like to re-use most of sdks' [DownloadActionOutputs](https://github.com/bazelbuild/remote-apis-sdks/blob/daf8fa09cc33/go/pkg/client/cas.go#L585) function in our client.
But we use digest of Directory instead of Tree, so let me add function to download Directory from digest.

Add DownloadDirectory function

---

go/pkg/tool/tool_test.go

We were using `os.TempDir()` (which gives a value `/tmp`) instead of `testing.TempDir()` (which will give a random tempdir like `/tmp/<uuid>-dir/`) and then we added code to remove the temp dir, so we were just clearing `/tmp/` accidentally which was the cause of the test failures.

 Use t.TempDir() instead of os.TempDir()

---

go.mod
go/pkg/balancer/BUILD.bazel
go/pkg/balancer/gcp_balancer.go
go/pkg/balancer/gcp_balancer_test.go

Not read locking this results in a race condition in writing / reading
to balancer.scStates map variable.
Test: Ran
bazelisk test --features race //go/pkg/balancer/... --test_output=streamed --test_timeout=10
and it fails without the fix to regeneratePicker().

Read lock before looping through scStates in regeneratePicker()

---

go/pkg/balancer/BUILD.bazel
go/pkg/client/batch_retries_test.go
go/pkg/client/cas.go
go/pkg/client/client.go
go/pkg/client/retries_test.go
go/pkg/flags/BUILD.bazel
go/pkg/flags/flags.go

Also tightening up the existing default values.

Customizing RPC timeouts per RPC via flags.

---

go/pkg/client/cas.go
go/pkg/client/cas_test.go
go/pkg/client/client.go
go/pkg/fakes/cas.go

Fixes #43 and #44, because this also doesn't query GetMissingBlobs for
previously uploaded blobs.

Deduping concurrent write requests.

---

go/pkg/client/BUILD.bazel
go/pkg/client/batch_retries_test.go
go/pkg/client/capabilities.go
go/pkg/client/cas_test.go
go/pkg/client/client.go
go/pkg/client/retries_test.go
go/pkg/digest/digest.go
go/pkg/fakes/exec.go
go/pkg/fakes/server.go

For now, only check digest function compatibility and set MaxBatchSize
accordingly. Fixes #99.
Still TODO: check API version compatibility, cache and execution
priorities once we implement those.

Reading server capabilities at client startup.

---

go/pkg/client/client.go
go/pkg/flags/flags.go
go/pkg/tool/tool.go
go/pkg/tool/tool_test.go

These changes are sufficient to persuade remotetool to interact with
my remote caching setup. Notably:
* TLS wiring added
* In cache-only mode, bazel does not upload input roots, so tolerate errors
* Show actions without results, to handle actions which failed
* Render a few interesting fields that were previously skipped

Add more TLS config flags, and support remote caching mode

---

go.mod
go/pkg/client/retries_test.go

This improves time for `//go/pkg/client:go_default_test` from 27.7s to 5.6s on 24C/48T linux machine.

Run retries tests in parallel

---

go/pkg/client/bytestream.go
go/pkg/client/cas.go
go/pkg/client/client.go
go/pkg/client/exec.go
go/pkg/flags/flags.go

This will effectively set the timeouts at 1 minute for
Write/Read/GetTree.

Fixing streamed RPC timeouts.

---

go/pkg/flags/flags.go

This is useful, e.g., for connecting to local servers without TLS (e.g.,
for debugging).

Add --service_no_security to connect to the RBE service without TLS

---

go/pkg/tree/tree.go
go/pkg/tree/tree_test.go

This is useful for some things - for example we've found Buildbarn's browser to be very helpful, but it requires the individual directory protos in an output to be uploaded in order to browse them, and the client doesn't have access to the Tree any more to construct this themselves.

Produce chunks for individual dir protos as well

---

go/pkg/client/cas.go

I think this is removed accidentaly in https://github.com/bazelbuild/remote-apis-sdks/commit/0dbc1039e6dad925ee9a461a66bbf1b2f35693f1 .

revive c.RPCOpts in GetTree

---

go/pkg/client/bytestream.go
go/pkg/client/cas.go

I think this is more appropriate fix for https://github.com/bazelbuild/remote-apis-sdks/commit/0dbc1039e6dad925ee9a461a66bbf1b2f35693f1 .

fix for #212

---

go/cmd/remotetool/main.go

When the string being written itself has % sign, using Fprintf()
results in go interpreting that %sign for string formatting.
Tested with an action that has % sign in its command.

Use os.Stdout.Write() when printing to stdout

---

go.mod
go/pkg/filemetadata/filemetadata.go
go/pkg/filemetadata/filemetadata_test.go
go/pkg/tree/tree.go

This is a prep step to address https://github.com/bazelbuild/remote-apis-sdks/pull/229#issuecomment-722923295. I find the code to handle symlinks a bit too complicated when `IsDirectory` is put inside the `FileError`, especially when symlink and directory are both true.

Refactor where IsDirectory is stored in the file metadata

---

go/pkg/tree/tree.go

Another cleanup for #229 .
Also lower-cased the member names in `fileNode`, `treeNode`.

tree: pull EmptyDirectoryMarker out of fileNode

---

go/pkg/filemetadata/BUILD.bazel
go/pkg/filemetadata/cache_posix_test.go
go/pkg/filemetadata/cache_test.go
go/pkg/filemetadata/filemetadata_test.go
go/pkg/reader/BUILD.bazel
go/pkg/reader/reader_test.go
go/pkg/testutil/BUILD.bazel
go/pkg/testutil/testutil.go

Internal Gazelle doesn't like it when packages have underscores in their names.

Renaming test_util to testutil

---

go/pkg/client/BUILD.bazel
go/pkg/client/client.go
go/pkg/client/tree.go
go/pkg/client/tree_test.go
go/pkg/client/tree_whitebox_test.go
go/pkg/command/command.go

Added `TreeSymlinkOpts` to control the behavior of tree construction.
To be backward compatible, symlink is preserved only when `TreeSymlinkOpts.Preserved` is explicitly set to `true`. By default, symlinks are converted into files.
Issue: #146

Support symlinks when constructing a Merkle tree.

---

go/pkg/reader/reader.go
go/pkg/reader/reader_test.go

Bugfix: this should fix the broken Windows unit test.

Closing the reader in the end of a read.

---

go/pkg/client/tree.go
go/pkg/client/tree_test.go
go/pkg/client/tree_whitebox_test.go

I believe what I did in #229 was wrong when handling the symlink target.
1. When we construct the `SymlinkNode`, `Target` should be relative to **the directory of the symlink**. #229 computed the path relative to `execRoot` instead. This is problematic when the target is an absolute path in the filesystem.
2. When we recursively call `loadFiles()` on the target, this time `path` should still be the part of target relative to `execRoot`.

Fix the way to compute the target path relative to the symlink

---

go/pkg/chunker/chunker.go
go/pkg/client/cas.go
go/pkg/client/cas_test.go
go/pkg/client/client.go
go/pkg/fakes/BUILD.bazel
go/pkg/fakes/cas.go
go/pkg/fakes/server.go

This follows the current tentative API. This PR potentially replaces #232

Add compressed writes to cas.go.

---

go/pkg/client/BUILD.bazel
go/pkg/client/cas.go
go/pkg/client/cas_test.go
go/pkg/fakes/cas.go

It follows the specs specified in bazelbuild/remote-apis#168, and
it is similar to #232. Note that while the API still has room to
change, it is mostly finalized and worth implementing.
A caveat of this implementation is that while the `offset` in reads
refers to the uncompressed bytes, the `limit` refers to the compressed
bytes.

Add compressed reads to cas.go.

---

go/pkg/client/cas.go
go/pkg/client/client.go

While the RE API addition of the API isn't ready, we can't
check for server Capabilities whether compression is supported.

Turn off compression by default.

---

go/pkg/client/cas.go

This is follow up of https://github.com/bazelbuild/remote-apis-sdks/pull/200
With this change, time of DownloadFiles improved from 46.4s to 37.7s on Windows for our dataset.
wihtout this PR: https://chromium-swarm.appspot.com/task?id=501c7e37a9526d10
with this PR:       https://chromium-swarm.appspot.com/task?id=501c93af586df010

write batch downloaded files in sorted order by path

---

go/pkg/client/cas_test.go
go/pkg/fakes/cas.go
go/pkg/fakes/server.go
go/pkg/reader/reader.go
go/pkg/reader/reader_test.go

The existing code had a couple issues:
1) An EOF from the underlying uncompressed data would trigger finalizing
a read of the compressed data - even though the compressed data itself
wasn't ready or finalized reading.
2) *After* the `Close` call on the encoder, which triggers the
compressed data to be available for reading, is when you have to
actually read the final chunks and pieces of data.
The test code was also faulty as it checked the bytes up to the length
of the code compressed data (instead of the test compressed data), which
was 0.
This issue never arove on the fakes servers as cas_test doesn't seem to
have File tests - this compression issue wouldn't show up on in memory
blob tests. Just in case, I also added further checks on fake CAS to
ensure compressed calls were actually …

Further write compression patch.

---

.bazelci/presubmit.yml
go/pkg/client/batch_retries_test.go
go/pkg/client/cas_test.go
go/pkg/client/client.go
go/pkg/client/retries_test.go
go/pkg/retry/retry.go

Also improving retry logging. Includes adding race/deflakes to presubmit
-- decided to make that two separate jobs for efficiency -- gorace detects
different kinds of errors than runs_per_test; combining them is too
costly (currently, impossible because we spawn too many goroutines for
gorace to work).

Deflaking,improving performance,refactoring.

---

go.mod
go.sum
go/pkg/reader/BUILD.bazel
go/pkg/reader/reader.go
remote-apis-sdks-deps.bzl

On some sample testing this compression performs ~4x faster
than "wasting" the encoders.

Add shared zstd encoder pools.

---

go.mod
go.sum
remote-apis-sdks-deps.bzl

github.com/klauspost/compress v1.11.16 has the following fix which
allows the syncpool implementation to free resources earlier:
https://github.com/klauspost/compress/commit/fa5ea64d60c615a664931521778e111b45a43dbc
Here's the corresponding syncpool update:
https://github.com/mostynb/zstdpool-syncpool/commit/66ec463a4df39aff4bd8ff888309877d3dce062e

upgrade zstd library version for earlier resource free'ing fix

---

go/pkg/client/BUILD.bazel
go/pkg/client/bytestream.go
go/pkg/client/cas.go
go/pkg/client/retries_test.go

The current configuration will try to use the offset of the _compressed_
blob as the new offset for retrying reads. However, the compressed RE
API wants the offset to refer to the _uncompressed_ blobs. Since the
compressed offset will usually be a lower number than the uncompressed
offset, we generally end up with a bigger blob than expected.
Since this Read interruptions are mostly transient (eg context deadlines
exceeded), our higher level retries have been mostly hiding the issue.
Also took the chance to beef up some comments around the thread tricky
compression code.
I'll _eventually_ add retries tests to compressed blobs writes retry tests :)

Fix compressed read retries in compressed blobs.

---

go/pkg/client/BUILD.bazel
go/pkg/client/cas.go
go/pkg/client/exec.go
go/pkg/rexec/rexec.go

Reverts bazelbuild/remote-apis-sdks#272
This doesn't work internally (error code is not properly wrapped). Will need to debug more.

Revert "Surfacing error details of the gRPC status"

---

WORKSPACE
go.mod
go.sum
go/pkg/client/BUILD.bazel
go/pkg/client/client.go
go/pkg/client/client_test.go
go/pkg/command/command.go
go/pkg/command/command_test.go
go/pkg/fakes/server.go
go/pkg/rexec/rexec.go

Versions 2.1 and 2.2 of the [Remote Execution API](https://github.com/bazelbuild/remote-apis/blob/1e9ccef3705c2c41a447aee0ddbe6810ccb7949d/build/bazel/remote/execution/v2/remote_execution.proto) introduce two changes:
* The Platform properties list can now be also set in the `Action` message (allowing servers to read the properties without dereferencing the `Command` message), and
* the `Action.output_{files, directories}` fields are now combined into `Action.output_paths`.
This bumps up the required version of `github.com/bazelbuild/remote-apis` to use v2.2 of `remote_execution.proto` and updates `exec.go` to populate those fields following the most recent version of the spec.
This is a breaking change for older implementations, but I wasn't sure what the preferred way of addressing this …

rexec: Update to REAPI v2.2

---

go/pkg/tool/tool.go

Tested: action that prints hello, before and after.

Tiny bugfix in remotetool: handle actions with no inputs

---

go/pkg/client/BUILD.bazel
go/pkg/client/cas.go

Testing on internal builds yielded improvements :)

Add shared zstd decoder pools.

---

go/pkg/client/cas_test.go
go/pkg/fakes/cas.go

This is follow up CL for
https://github.com/bazelbuild/remote-apis-sdks/pull/184

fake: follow spec around empty blob

---

go/pkg/rexec/rexec.go
go/pkg/rexec/rexec_test.go

This function is useful when we only want to know the output digests
without actually downloading them.
Test: Added unit tests, also integ test with re-client.

Add utility function to return output file digests for a given exec context

---

go/pkg/client/cas.go

Doing so before doing the err check results in segmentation fault when
the defered afterDownload() function is run.
Test: n/a, debugging / fixing it based on stack trace from user bugs.

Populate stat after err checking is complete

---

go/pkg/client/tree.go
go/pkg/client/tree_test.go
go/pkg/client/tree_whitebox_test.go
go/pkg/fakes/exec.go
go/pkg/fakes/server.go

This gets rid of a few bottlenecks:
1. Recursion -> iteration. I'm not sure how much of a bottleneck this is, 
but in practice recursion is much more expensive than iteration.                                                                                                                                                                                                                    
2. Replace ioutil.ReadDir, which will both sort and stat files, so
unnecessarily slow.                                                                                                                                                                                                                                                                 
3. Remove lots of filepath operations, including Cleans. All the …

Revamp loadFiles for performance.

---

go/pkg/cas/client.go
go/pkg/cas/upload.go

Add cas.Client with a structure, but without actual implementation.
The TODOs will be implemented in subsequence CLs and in parallel.
Unlike client package, NewClient() function in this package does not
option. Rationale:
- the "options" approach pollutes the godoc page: a new type,
its Apply() function, the DefaultXXX constant.
In contrast, a simple Config struct is much more compact and has
minimal footprint on the number of symbols in the godoc page.
- GCP libraries use the approach used in this package
- https://pkg.go.dev/cloud.google.com/go/spanner#NewClientWithConfig
- https://pkg.go.dev/cloud.google.com/go/bigtable#NewClientWithConfig
- the options approach is used only for common options

[cas] Add cas package

---

go/pkg/cache/cache.go
go/pkg/cache/cache_test.go
go/pkg/cache/singleflightcache/singleflightcache.go
go/pkg/cache/singleflightcache/singleflightcache_test.go
go/pkg/cas/upload.go
go/pkg/filemetadata/cache.go

Simplify and optimize singleflightcache implementation: replace two
sync.Maps and an N+1 sync.RWMutexes, with one sync.Map and N sync.Once.
Do other simplifications as well.
Remove dead code / impossible conditions, e.g. "unexpected type found in
lock map". Use that to simplify the function signatures, e.g. don't
return an error (and thus simplify callsites and tests) when an error
is impossible.
In filemetadata/cache.go, fix the bug that it resets all namespaces.
`cache.Cache.Reset` was inherently racy because it was overwriting a mutex (without holding another mutex).
Replace with safe ns-level resetting.

Simplify caching packages

---

go/pkg/cas/client.go
go/pkg/cas/upload.go
go/pkg/client/client.go
go/pkg/retry/BUILD.bazel
go/pkg/retry/retry.go

Move ShouldRetry impl from client package to retry package, since it is
generic. Reuse it in the cas package.

[cas] Add retries

---

go/pkg/cas/BUILD.bazel

Include the `retry` package. This CL should fix the CI.
This change should have been a part of https://github.com/bazelbuild/remote-apis-sdks/commit/fd877b05ba2ed611f6d34e711da05917b729eff9

[cas] Update BUILD.bazel

---

go/pkg/cas/BUILD.bazel
go/pkg/cas/client.go
go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

Partially implement scheduleUpload - for small blobs.
Use bundler.Bundler to bundle blobs together.

[cas] Implement batch upload

---

go/pkg/cas/client.go
go/pkg/cas/upload.go

Put the buffers in a pool which is defined the Client level, such that
all uploaders (and downloads in the future) can reuse the same pool.
The pool is not global because the IO size is configured at the client
level.

[cas] Reuse file read buffers

---

go/pkg/cas/client.go
go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

Add UploadOptions which is optional configuration for Upload() func.
Move PreserveSymlinks and AllowDanglingSymlinks there. This way the
same Client can be reused with different options, i.e. the callsite
can reuse caches.
This slightly simplifies tests too.
In the next CL, predicate will be added to UploadOptions.

[cas] Add UploadOptions

---

go/pkg/cas/client.go
go/pkg/cas/upload.go
go/pkg/client/capabilities.go
go/pkg/digest/digest.go

Move common digest function checking code to digest package.
For consistency, rename `ClientConfig.BatchBlobsBatchSize` to
`MaxBatchTotalSizeBytes` which is the name used in proto.

[cas] Implement ServerCapabilities check

---

go/pkg/cas/client.go
go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

First of all, this CL fixes a bug that max-bytes was confused with
max-count, in (*Client).Upload().
Stepping back, the reason is that the RPC config fields are long and
confusing. Earlier version of the code attempted to deal with this by
partially following a rule that a per-RPC config fields starts with the RPC
name, but clearly this wasn't enough.
Introduce RPCConfig struct which contains RPC-specific configuration,
namely concurrency, max-size, max-count and timeout. Use the struct
as a type of two new fields: ClientConfig.FindMissingBlobs and
ClientConfig.BatchUpdateBlobs, which match RPC names exactly.
This is different from client package's approach, which is having a
map[string]RPCConfig. It was considered, but it causes non-type-safe
code, e.g. using string literals to refer to …

[cas] Add RPCConfig

---

go/pkg/cas/client.go
go/pkg/cas/upload.go

Respect ClientConfig.FindMissingBlobs.Concurrency by adding a semaphore.

[cas] Limit FindMissingBlobs concurrency

---

go/pkg/cas/client.go
go/pkg/cas/ioutil.go
go/pkg/cas/upload.go
go/pkg/digest/digest.go

Passing explicit []byte buffers to various functions does not guarantee
buffered reads from an io.Reader. In particular. io.CopyBuffer may
ignore the passed buffer. As a result, the file IO size might get
ignored.
Move buffering deeper by using bufio.Reader. Use it throughout.
Replace a sync.Pool of []byte with a pool of bufio.Readers.
Ungeneralize readSeekCloser since we no longer read from *os.File
directly. Still, preserve seeking (only relative to start) because streaming files must start
with the current-offset-on-the-server.

[cas] Move file IO buffering deeper

---

go.mod
go.sum
remote-apis-sdks-deps.bzl

We have to figure out the bazel-foolness to recompile these protos,
instead of using the pb.go available. On the meanwhile, this updates
it to the latest version where the .go is in sync with the .pb.

Update RE dependency to get latest go bindings.

---

WORKSPACE
go.mod
go.sum
go/api/command/BUILD.bazel
go/cmd/remotetool/BUILD.bazel
go/cmd/rexec/BUILD.bazel
go/pkg/actas/BUILD.bazel
go/pkg/balancer/BUILD.bazel
go/pkg/balancer/proto/BUILD.bazel
go/pkg/cache/BUILD.bazel
go/pkg/cas/BUILD.bazel
go/pkg/chunker/BUILD.bazel
go/pkg/client/BUILD.bazel
go/pkg/command/BUILD.bazel
go/pkg/digest/BUILD.bazel
go/pkg/fakes/BUILD.bazel
go/pkg/filemetadata/BUILD.bazel
go/pkg/flags/BUILD.bazel
go/pkg/moreflag/BUILD.bazel
go/pkg/outerr/BUILD.bazel
go/pkg/portpicker/BUILD.bazel
go/pkg/reader/BUILD.bazel
go/pkg/retry/BUILD.bazel
go/pkg/rexec/BUILD.bazel
go/pkg/testutil/BUILD.bazel
go/pkg/tool/BUILD.bazel
go/pkg/uploadinfo/BUILD.bazel

This uses the newer (nicer) gazelle naming scheme.

Update golang, rules_go and gazelle.

---

go/pkg/cas/client.go
go/pkg/cas/client_test.go
go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

grpc package does not have native support for per-request timeouts for
streaming RPC. Add a helper function to accomodate that.
The func is not specific to CAS, but it wasn't obvious which package
is a better place for it.

[cas] Implement per-request timeouts in a stream

---

go/pkg/cas/client.go
go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

Currently `cas.Client` struct embeds ClientConfig struct.
As a result, IDE auto-completion for `cas.Client` suggests a bunch
of low-level uninteresting fields, so `Upload()` is buried
among them.
Unembed the `ClientConfig` struct.

[cas] Unembed cas.Client.ClientConfig.

---

go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

"Callback" may mean many things. The name does not entail *when* it is
called. The next CL will introduce another callback which is called
*after* a blob is uploaded. Rename "Callback" to "Prelude" to avoid
ambiguity.

[cas] Rename UploadOptions.Callback to Prelude

---

go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

Currently PathExclude regexp is incorporated into the cache key
unconditionally. However, pathExclude isn't used if the path is a regular file.
Thus do not incorporate PathExclude into the cache key in this case.

[cas] Read files once

---

go/pkg/cas/upload.go

Refactor the code to pass new `pathInfo` struct around which is a tuple of
`absPath` and `os.FileInfo`. This is a preparation for another CL which actually
adds new functionality, and uses the new struct.

[cas] Use pathInfo struct

---

go/pkg/cas/upload.go

Refactor `batchBundler` to bundle `uploadItem`s instead of
`repb.BatchUpdateBlobsRequest_Request`.
This CL is a pure refactoring, and a preparation for another CL
which actually adds new functionality.

[cas] Refactor batchBundler

---

go/pkg/cas/upload.go

Do not force users to make `PathExclude` conditional on the OS,
by normalizing paths to use forward-slashes before checking `PathExclude`.

[cas] PathExclude: use forward slashes

---

go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

Rename UploadInput to PathSpec, which specifies a subset
of the file system. Also remove UploadInput.Content as it is not
critical for most use cases and complicates more important things.

[cas] Rename UploadInput to PathSpec

---

.github/workflows/golangci-lint.yml

This is to ignore existing warnings.

golangci-lint.yml: enable only-new-issues

---

WORKSPACE
go.mod
go.sum
go/pkg/reader/reader_test.go
remote-apis-sdks-deps.bzl

This includes a [bugfix](https://github.com/mostynb/zstdpool-syncpool/commit/4c85d3ef27395d3450baaf471e52fafeceb3c6e0) for `DecoderWrapper.Close`, where it was only returning Decoders to the pool if `Decoder.Reset(nil)` failed, and upgrades github.com/klauspost/compress which has had a few zstd improvements.

Upgrade zstdpool-syncpool for DecoderWrapper.Close bugfix

---

go/pkg/cas/upload.go

Fix joinFilePathsFast where the first path is the root.
We don't expect it in production, but it happens in tests.

[cas] Fix joinFilePathsFast

---

go/pkg/cas/upload.go

https://github.com/bazelbuild/remote-apis-sdks/pull/345
removed filepath.Abs call, but it has a side effect that we no longer
clean the path. Clean it explicitly.

[cas] Clean PathSpec.Path

---

go/pkg/cache/singleflightcache.go
go/pkg/cache/singleflightcache_test.go
go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

The callers of `Client.Upload` need the digest back in order to
pass it to another system which would fetch the uploaded files.
Add `cas.UploadInput.OnDigest` callback, called when a digest is computed.
Note that by the time `OnDigest` is called, the item is not fully uploaded yet.
It is generally hard to detect when a tree is fully uploaded because
file uploads happen in arbitrary order. In particular, a blob for a
parent directory may be uploaded before its children.
Still, this is enough for the purpose.
Returning digests from `Upload()` function was also considered, but it
is getting complicated quickly because the callsite needs to know
uploadItem->digest association.
Another considered alternative is to add something like
`UploadInput.Digest digest.Digest` which is populated by …

[cas] Add UploadResult.Digest

---

go/pkg/cache/singleflightcache.go

Some functions in singleflightcache.go name their return values and some
don't. Name them in all functions for consistency.

Add return value names in singleflightcache

---

go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

Instead of returning a possibly nil digest, introduce a new error
ErrNoDigest and return that instead. It simplifies most callsites: now
they check only 2 cases instead of 3.

[cas] Simplify UploadResult.Digest() signature

---

go/pkg/cas/upload.go
go/pkg/cas/upload_test.go

UploadResult.Digest(PathSpec) semantics turned out to be complicated.
Remove it, rename PathSpec back to UploadInput and add
UploadInput.Digest(relPath string). The latter is easy to use, e.g.
the digest for UploadInput.Path is just UploadInput.Digest(".").
Since UploadInputs are sent to the client over the channel, the caller
might want to produce them in different goroutines, where each goroutine
might want to read the computed digest back. Since those goroutines
don't necessarily know when Upload() call returns, add
UploadInput.DigestComputed() function that returns a channel which is
closed when the digest for the UploadInput is computed.
This means Upload() call can be long-lived and multiple goroutines can
upload files independently.
Add more tests.

[cas] Refactor Digest()

---

go/pkg/client/cas.go
go/pkg/client/cas_test.go

This reverts commit e155d015bcc4c9eb9978572422e3404f26220700.
gRPC errors are... hard. And the gRPC team isn't willing to support
wrapping, which leads to complicated handling. See
https://github.com/grpc/grpc-go/issues/3616.
I'll send a different PR to add stack traces to these grpc errors.

Revert "Add useful error message for uploading files. (#339)"

---

go/pkg/client/cas_test.go
go/pkg/client/client.go

While gRPC error codes aren't wrapper-friendly (see
https://github.com/grpc/grpc-go/issues/3616), we still
want to be able to get more context from errors.
Adding stack traces on their messages was the easiest way
I thought of that'd maintain backwards compatibility.

"Wrap" gRPC error codes.

---

go/pkg/cas/client.go

I think we want to specify larger value for streamBufSize (e.g. 4MiB)

allow to use streamBufSize larger than 32KiB

---

go/pkg/cas/client.go
go/pkg/cas/upload.go

Only one file upload concurrency seems too strict.
With this, uploading 16 1GiB files with compression took 91s on HDD Linux GCE.
https://chromium-swarm.appspot.com/task?id=54c6ff9164a1e010
Without this, uploading 16 1GiB files with compression took 208s on HDD Linux GCE.
https://chromium-swarm.appspot.com/task?id=54c6f96c61139510

use semaphore for large file upload

---

go/pkg/cas/upload.go

Zstd encoder seems reading some amount of file content before uploader
got response about existing file from byte stream client.
This avoids such unnecessary file read.

cas: check file existence for large file

---

.bazelci/presubmit.yml

This fixes the Bazel CI pipeline, which turned red when we removed the pre-installed Go version in the base image.

Download Golang during CI job

---

go/pkg/client/tree.go
go/pkg/client/tree_test.go

The added test returns rood digest "24b2420bc49d8b8fdc1d011a163708927532b37dc9f91d7d8d6877e3a86559ca/73", which includes an empty dir "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/0" at path ".".
This change ignores empty dir if it's root dir.

Fix ComputeMerkleTree to handle empty root

---

remote-apis-sdks-deps.bzl

The change is required to address recent build failures
that are caused by compute module being carved out of
cloud/google.com/go:
https://github.com/googleapis/google-cloud-go/pull/5273

Added com_google_cloud_go_compute dependency

---

go/pkg/fakes/server.go

- Adds OutputDirectories to the action result. 
- BuildDir recursively iterates through the directory to build a directory tree, and obtains the digest of that directory tree.

Add support for output directories in fake server.

---

go/pkg/client/exec.go

Retrying based on an operation error is always incorrect, although
mostly harmless. Once an operation has an error, it is marked as Done
and should never be unmarked, so retries will simply fetch the same
operation (with the same error) again.

Remove execution retries based on operation errors.

---

go/pkg/client/tree.go
go/pkg/client/tree_test.go

Currently if a treeNode has children and is also marked as an empty directory (virtual input), ComputeMerkleTree returns an error. This behavior is actually inconsistent, since it relies on the order of inputs checked in a loop over a map. This PR makes the behavior consistent and ignores empty directory virtual inputs if physical inputs exist under them. Note that physical input precedence is already enforced in ComputeMerkleTree where a virtual input has the same name as a physical input. This PR extends this behavior to virtual inputs that are ancestors to physical inputs.

Ignore empty directory virtual inputs if inputs exist under them.

---

go/pkg/client/cas.go

`wt.dg` is not finalized in this line.
This is to investigate https://crbug.com/1297621

show correct digest in error

---

go/pkg/client/cas.go

In case the machine runs out of disk space, the write error will be
captured in the done channel, but is suppressed if no other errors
were encountered. This PR exposes the error in the done channel.

Expose errors in closing the Writer.

---

go/pkg/client/tree.go
go/pkg/client/tree_test.go

Currently the output directory tree's child nodes are appended randomly in `ComputeOutputsToUpload`. This changes the `ComputeOutputsToUpload` to build the directory trees based on the lexical order of the sub directories so that we will get a consistent output.
The new test case added in `TestComputeOutputsToUploadDirectories` would give the following result before the changes:
```
INFO: Found 1 test target...
--- FAIL: TestComputeOutputsToUploadDirectories (0.05s)
--- FAIL: TestComputeOutputsToUploadDirectories/Directory_tree_preserves_natural_order (0.01s)
tree_test.go:1813: ComputeOutputsToUpload(...) directory digests are not consistent got:[cbf9cdd9a275d4417d46f98b673db3010b6ed50b740a5a0b728b16d86270c51c cf74177e895f8aad5f2dd165cc269113bee533671ad25ee25ae9234033ad0570 …
```

Fix ComputeOutputsToUpload to build directory tree consistently

---

go/pkg/filemetadata/filemetadata.go

Fallback on old file hashing in the event the xattr digest can't be read.

xattr digest fallback

---

go/pkg/client/cas.go
go/pkg/client/cas_test.go

Two problems:
1. We are incorrectly writing to a file if the destination file has more
content than the source file during copying.
2. We aren't updating the timestamp of the file when the destiination
file has zero bytes.
Both these would be fixed by just setting the file open mode to
os.O_TRUNC which would truncate the file if it already exists.
Test:
1. Unit tests
2. Tested in Android build with:
```
rm -f out/reproxy* && touch frameworks/opt/net/voip/src/java/com/android/server/sip/SipWakeupTimer.java && RBE_v=3 RBE_instance="projects/foundry-x-experiments/instances/default-instance" RBE_use_unified_cas_ops=false RBE_use_batches=false RBE_METALAVA=true m out/soong/.intermediates/frameworks/base/api-stubs-docs-non-updatable/android_common/metalava/check_last_released_api.timestamp
``` …

Always set file modified time after writing to a file

---

go/pkg/client/client.go
go/pkg/fakes/server.go
go/pkg/filemetadata/filemetadata_test.go

This is to also indicate the type of authenticated used by the SDK to
connect to the RBE so that clients of the SDK can report better error
messages to indicate how the authentication failure can be fixed.
Test: Applied this change in re-client and confirmed that the returned
object has the proper auth type set.

Returned a customized error when initializing a new client

---

.bazelci/presubmit.yml
.githooks/pre-commit
check-golint.sh
go/pkg/client/client.go
go/pkg/client/client_context.go
go/pkg/digest/digest.go
go/pkg/fakes/exec.go
go/pkg/reader/reader.go
go/pkg/testutil/testutil.go

This is so that we catch lint issues here before we import the SDK to
google3. Also added the lint check to presubmit hooks just like how we
do for gofmt.

Fix all lint errors and enable golint

---

go/pkg/client/cas.go

We always lookup the absolute path, so when we update the cache, we
should also update it to be the absolute path.
Test: Ran the repro in bug b/228312861

Fix what path gets updated in cache

---

go/pkg/client/cas.go
go/pkg/command/command.go
go/pkg/rexec/rexec.go

Adds functions to retrieve outputs and download specified outputs instead of the ones in working dir. Also adds a new command option for preserving mtimes of unchanged outputs.

Download Specified Outputs

---

go/pkg/client/BUILD.bazel
go/pkg/client/tree.go
go/pkg/client/tree_test.go

Previously if `TreeSymlinkOpts.Preserved` was set to `true`, symlinks pointing outside of the exec root would always be rejected. However, it can be useful to preserve symlinks by default while replacing them with the targeted file if the targeted file is outside of the exec root.
So add a new `TreeSymlinkOpts.MaterializeOutsideExecRoot` option that enables this behavior if set to true.
See https://crbug.com/1216363 for context on why this is useful.

Optionally process symlinks pointing outside exec root

---

go/pkg/client/BUILD.bazel
go/pkg/client/cas.go
go/pkg/client/cas_upload.go
go/pkg/client/client.go

Moved internal implementations to separate methods to allow public methods to select implementations based on feature flags.
No functional changes made.
This is a stop-gap change to merge cas/upload.go into client pkg.

Refactor public methods to delegate to impls

---

go/pkg/client/BUILD.bazel
go/pkg/client/bytestream.go
go/pkg/client/bytestream_test.go
go/pkg/client/cas_upload.go
go/pkg/client/client.go
go/pkg/client/retries_test.go

Update writeChunked method in bytestream.go to allow resumable upload with ByteStream Write API.
I also added a new struct ResumableWriteOpts and it’s added to Client to keep track of write offset so that we can start writing data at an arbitrary offset.

Update writeChunked method in bytestream.go to allow resumable upload with ByteStream Write API.

---

go/pkg/reader/reader.go
go/pkg/reader/reader_test.go

**Note: this introduces a behavior change in addition to the bug fix described below. After `compressedSeeker.Read()` returns an error, subsequent calls continue to drain the internal buffer until it announces EOF, whereas before the method short-circuited and reported the last error on subsequent calls. Since this is an internal package, it's unlikely that there have been any external dependencies on this behavior.**
There was a subtle bug in the `compressedSeeker` class that caused retried upload requests to occasionally fail under a very specific set of conditions:
1. The file being uploaded must be greater than the client's `MaxBatchSize` so it's not batched together with other files (compression is always disabled for files that are batched together).
2. Upload compression must be …

[reader] Fix compressed reader retries

---

go/pkg/command/command.go
go/pkg/fakes/server.go
go/pkg/rexec/rexec.go
go/pkg/rexec/rexec_test.go

Add output symlinks to the Metadata struct. Also add tests to ensure symlink behavior is correct.

Add output symlinks to the action metadata.

---

go/pkg/cas/BUILD.bazel
go/pkg/cas/config.go
go/pkg/client/BUILD.bazel

These configuration values will be used by the implementation which will posted later.
Reusing existing configuration structs risks overloading them or changing their semantics.

New config file for pluggable CAS implementation

---

go/pkg/client/cas_test.go
go/pkg/client/cas_upload.go
go/pkg/client/client.go

This PR removes the behavior to batch FindMissingBlobs calls as part of unified uploads. This behavior has been benchmarked to slow builds down by ~2x. FindMissingBlobs is cheap and calling it per UploadIfMissing call is a reasonable way to prune upload requests going into a buffer, specially that the blob cache hit rate is expected to be very high.
This PR also fixes the handling of UnifiedUploads / UnifiedDownloads client options to avoid complicated restart logic.

Avoid delays in unified uploads due to batching of FindMissingBlobs.

---

go/pkg/errors/BUILD.bazel
go/pkg/errors/errors.go
go/pkg/io/impath/BUILD.bazel
go/pkg/io/impath/impath.go
go/pkg/io/impath/impath_test.go

This implementation helps eliminate all ambiguity stemming from using strings as path, namely differentiating between absolute and relative paths.

introduce immutable path package

---

go/pkg/client/tree.go

Very similar to the handling of `t.files`, seems to have just been missed in this case.

Handle symlinks in packageDirectories

---

go/pkg/io/walker/BUILD.bazel
go/pkg/io/walker/filter.go
go/pkg/io/walker/filter_test.go
go/pkg/io/walker/stack.go
go/pkg/io/walker/walker.go
go/pkg/io/walker/walker_test.go

The package provides an API to walk the file system in depth-first style traversal. This encapsulates IO and implementation naunces and exposes a concise interface for clients.
The DFS traversal and the deferring behaviour is leveraged in the CAS upload implementation that will posted later.

introduce the file system walker package

---

go/pkg/cas/config.go
go/pkg/contextmd/contextmd.go
go/pkg/io/walker/walker.go
go/pkg/io/walker/walker_test.go

Instead of returning a nil context, I changed the signature such that an explicit primary context is provided to derive from or return as is.

linter fixes

---

go/pkg/symlinkopts/BUILD.bazel
go/pkg/symlinkopts/opts.go
go/pkg/symlinkopts/opts_test.go

The package allows defining a set of options that cover all supported
cases by the SDK. The options instance is immutable and can only be created using
predefined set to ensure every instance has a valid set of options.

introduce symlink options package

---

go/pkg/command/command.go
go/pkg/fakes/server.go
go/pkg/rexec/rexec.go
go/pkg/rexec/rexec_test.go
go/pkg/tool/tool_test.go

Introducing two digest fields in Metadata for stderr and stdout. Modified the Set method, so that instead of returning cmdDg, and acDg, it also returns stderrDg and stdoutDG. All the other unit tests are modified accordingly.
Bug: b/172888682
Tested-by: run unit test locally

add stderrDg and stdoutDg in MetaData

---

go/pkg/filemetadata/filemetadata_test.go

Resolves `Failed to write to file: open test.txt: permission denied` error

Move targetFile in XAttr test to t.TempDir

---

BUILD.bazel
WORKSPACE
go_deps.bzl

It is clearer when the sdk is not the only go module being imported into a workspace.

use fqn for sdk deps starlark function

---

go/pkg/casng/BUILD.bazel
go/pkg/casng/batching.go
go/pkg/casng/batching_write_bytes_test.go
go/pkg/casng/throttler.go
go/pkg/casng/uploader.go

Byte streaming is used to upload large files that do not fit in a batching request.
This implementation avoids using the chunker package by leveraging the streaming nature of IO buffering.
Furthermore, error handling is more robust in this implementation since all errors are handled while ensuring a graceful cancelation when necessary.

casng, byte streaming implementation

---

go/pkg/casng/BUILD.bazel
go/pkg/casng/batching.go
go/pkg/casng/config.go
go/pkg/casng/pubsub.go
go/pkg/casng/streaming_query.go
go/pkg/casng/streaming_query_test.go
go/pkg/casng/uploader.go

The query processor provides a streaming interface to query the CAS for digests.
Multiple concurrent clients can use the same uploader instance at the same time.
The processor bundles requests from multiple concurrent clients to amortize the cost of querying the batching API. That is, it attempts to bundle the maximum possible number of digests in a single gRPC call.
This is done using 3 factors: the size (bytes) limit, the items limit, and a time limit. If any of these limits is reached, the processor will dispatch the call and start a new bundle. This means that a request can be delayed by the processor (not including network and server time) up to the time limit. However, in high throughput sessions, the processor will dispatch calls sooner.
To properly manage multiple concurrent …

casng, query processor

---

go/pkg/client/tree.go

Tiny cleanup in preparation for fixing https://github.com/bazelbuild/remote-apis-sdks/issues/460

noop/cleanup: use fileSysNode in treeNode

---

go/pkg/client/bytestream.go
go/pkg/command/command.go
go/pkg/fakes/BUILD.bazel
go/pkg/fakes/exec.go
go/pkg/fakes/logstreams.go
go/pkg/fakes/server.go
go/pkg/outerr/outerr.go
go/pkg/outerr/outerr_test.go
go/pkg/rexec/BUILD.bazel
go/pkg/rexec/rexec.go
go/pkg/rexec/rexec_test.go

I'm adding support for stdout/stderr log streaming to RBE. This change allows the client to receive stdout/stderr streamed in near-real-time while the action is running, rather than waiting until the action is complete and then downloading stdout/stderr from CAS.
The initial motivation for this PR is that our integration tests and other diagnostic tools use this SDK. So I need support for log streaming here to support those uses.

Add support for streaming stdout/stderr.

---

go/pkg/fakes/server.go
go/pkg/tool/tool_test.go

Bug was introduced in https://github.com/bazelbuild/remote-apis-sdks/pull/161.
Fake input files were never actually written to disk, like they were supposed to.

Fixing bug in fake and integration test

---

go/pkg/fakes/server.go
go/pkg/tool/BUILD.bazel
go/pkg/tool/tool.go
go/pkg/tool/tool_test.go

Includes https://github.com/bazelbuild/remote-apis-sdks/pull/473 because I couldn't figure out how to send a PR chain, sorry!
- adds a test for DownloadAction
- uses the `fakes.InputFile` whenever appropriate
- fixes the `ExecuteAction*` tests to not depend on implementation of the fake, and instead to mimics the user journey (downloading the inputs locally, then changing them).
- minor cleanups such as avoiding marshalling protos when unnecessarily, inlining small constants in tests, etc.
What I was actually doing is fixing https://github.com/bazelbuild/remote-apis-sdks/issues/460, but that PR got a bit too big with unrelated fixes and cleanups, so I decided to split these out.
Thank you!

tool test: improving coverage, cleanups, minor fixes

---

go/pkg/fakes/cas.go
go/pkg/rexec/rexec.go
go/pkg/rexec/rexec_test.go
go/pkg/tool/tool.go

The server may terminate the streaming request before sending available
bytes, which prevents the download fallback from getting them.
This change implements a resuming fallback to download the remainder of
the streams.
Additionally, the digests of the out and err streams will be printed in
the output of `execution_action` command to allow the user to access
them even if the remote execution fails, in which case they will not be
retrievable by `show_action`.

fix regression in downloading out/err streams

---

go/pkg/casng/pubsub.go
go/pkg/casng/streaming_query.go
go/pkg/casng/uploader.go
go/pkg/filemetadata/filemetadata_test.go

There are three deadlock fixes in this change. The first is described in code comments.
The second was caused by a regression in `excludeTag` function where it mutated the underlying array that is shared with the caller. This caused a tag to be removed and a tag to be duplicated, which eventually left some workers waiting indefinitely for messages that were never delivered. It also caused other workers to have more responses than expected which manifested as negative counts in the dispatcher.
The third was a potential deadlock I spotted while in `wait` method for `pubsub`, which would hold a read lock until a done signal is sent, potentially blocking any writes what should trigger said done signal.

deadlock fix and cleanup

---

go/pkg/casng/BUILD.bazel
go/pkg/casng/batching.go
go/pkg/casng/node_slice_cache.go
go/pkg/casng/streaming_upload.go
go/pkg/casng/upload_digester.go
go/pkg/casng/upload_dispatcher.go
go/pkg/casng/uploader.go
go/pkg/casng/util_test.go

This change is the first in a series to break down the upload code path. Subsequent changes will implement the methods in the order of the data flow.

casng, scaffold upload path

---

go/pkg/flags/BUILD.bazel
go/pkg/flags/flags.go

KeepAlive functionality sends periodic pings to the server over the transport layer.

Add KeepAlive support

---

go/pkg/casng/upload_dispatcher.go

The dispatcher routes requests between three different components: the digester, the gRPC workers, and the publishers.
The digester sends incoming blobs that need to be uploaded. The dispatcher routes those to either the batching gRPC worker, which handles small files, or to the streaming gRPC worker, which handles large files.
The gRPC workers upload the blobs to the remote server and forward the responses back to the dispatcher. The dispatcher then routes each response to all relevant requesters (a response may be associated with multiple requests).
The dispatcher is also responsible for routing control signals. It keeps track of the number of blobs that were routed for each requester and match that with the number of responses to the same requester. Once the requester signals that it's …

casng, implement the dispatcher

---

go/pkg/cas/upload.go
go/pkg/client/bytestream.go
go/pkg/client/cas_download.go
go/pkg/client/cas_upload.go
go/pkg/client/client.go
go/pkg/client/client_test.go
go/pkg/rexec/rexec.go

According to the spec, the leading slash must be omitted if the instance name is empty. Fixes #489

fix resource names with empty instance name

---

go/pkg/casng/batching.go
go/pkg/io/impath/impath.go
go/pkg/rexec/rexec.go

When casng is used via LERC (local execution remote cahcing), the code expects shared state to be set which I missed while testing with the remote strategy.
Tested with a local LERC build against Android.

casng, ensure shared state is set

---

go/pkg/casng/batching.go
go/pkg/casng/batching_upload_test.go
go/pkg/io/impath/impath.go
go/pkg/io/impath/impath_test.go

A few corner cases were not handeled properly.
The original one was not removing the leading slash after stripping
workingDir.
However, a more interesting one was that paths being outside workingDir,
but still under root, which could translate to partial replacements of
the workingDir path, which is a valid case, contrary to what I thought.
Reverted to using proper filepath APIs.

casng, fix resolving remote paths

---

go/pkg/client/client.go

We're connecting to CASService in this case, which is explicitly different from Service. The logic is correct, but the logging isn't.

Tiny logging bug-fix

---

go/pkg/client/capabilities.go
go/pkg/client/cas_download.go
go/pkg/client/cas_test.go
go/pkg/client/cas_upload.go
go/pkg/client/client.go
go/pkg/fakes/cas.go

Previously, BatchDownloadBlobs() wasn't properly recording the compressed download size. To fix it, I've introduced a new public interface called BatchDowloadBlobsWithStats(), which will return statistics on the downloaded blob size in addition to the actual content.
As part of this, I also realized that tests are non-existent for compressed BatchDownloadBlobs() and added them.
In a subsequent change, I'll fix BatchUploadBlobs() as well.
TESTED: Unit test

Fix stats in BatchDownloadBlobs call

---

go/pkg/client/tree.go
go/pkg/client/tree_test.go
go/pkg/client/tree_whitebox_test.go

If a filepath includes a symlink to a directory, that symlink is converted to a directory in the computed Merkle tree. This is fine unless symlink preservation is turned on, in which case any process that expects a symlink might fail.
For example, if `/a/b/c.go` is loaded and `b->bb`, the Merkle tree will only have b as a directory node and it will not include bb. If /a/b and /a/b/c.go are loaded, the server will fail to write both a directory and a symlink to the same path `/a/b`. The symlink comes from loading `/a/b` and the directory comes from loading `/a/b/c.go`.
The correct Merkle tree in this case should look like:
```
a
|_b->bb
|_bb
|_|_c.go
```
That is, any intermediate symlink to a directory appears in the tree exactly once as a symlink. I.e. it never appears as a directory. …

fix preserving intermediate symlinks

---

go/cmd/remotetool/main.go
go/pkg/tool/tool.go
go/pkg/tool/tool_test.go

Currently, if output path not exist, download action just fail. This CL auto create the missing output path, and if it is already exist, it will ask user to type yes or y to overwrite it.

Update tool.go to create output path if not exist

---

go/pkg/tool/tool.go

```
compilepkg: nogo: errors found by nogo during build-time code analysis:
go/pkg/tool/tool.go:384:11: github.com/google/glog.Infof call has arguments but no formatting directives (printf)
```

Add missing formatting directives

---

go/pkg/tool/tool.go

Save show_action result while download action

---

go/pkg/client/tree.go
go/pkg/client/tree_test.go

We want to ignore files that don't have read permissions rather than returning an error, as it is likely that the file is not needed if it can't be read.
Bug: b/308481142

Ignore files without read permissions

---

go/pkg/flags/flags.go

When PerRPCCreds is used, we are already setting it as part of DialParams, so we don't have to once again include it as part of clientopts when creating the connection.
When included again as part of clientopts, it results in gRPC adding duplicate Authorization header to the requests.
Issue: https://github.com/bazelbuild/reclient/issues/27 (thanks to @MarshallOfSound for debugging this)
Tested: I build with this, ran a sample command and confirmed with mitmproxy that authorization header wasn't repeated.
With this fix:
Without this fix:

Ignore setting PerRPCCreds as clientopts

---

go/cmd/remotetool/main.go
go/pkg/tool/tool.go

Followup to https://github.com/bazelbuild/remote-apis-sdks/pull/532
This does the simplest thing possible for now -- we can always add more keys by creating a custom struct that we return from all tool operations, and marshalling that as json.

remotetool: add --json output

---

go/pkg/tool/tool.go

The command is already templated. Formatting again would complicate sanitization.

minor: remove unnecessary format

---

go/pkg/fakes/cas.go

`GetTree` was iterating over the `FileNode`s and trying to parse the blob as a `Directory`, it should only need to iterate over the `DirectoryNode`s. It was also adding the `Directory` to the `res`ult list when adding and removing the `Directory` from the queue, doubling the output.
The output now matches the RBE server, at least for a simple example.

Fix GetTree fakes

---

go/pkg/rexec/rexec.go

Avoid racing in fake
re-client `reproxy_test` unit test has been suffering racing issues for long time,
This change will fix the data racing issue, and make most of the unit test there can run with t.parallel()
Test: import to re-client and run  //internal/pkg/reproxy:reproxy_test with race detection.

Avoid racing in fake package

---

go/pkg/client/cas_upload.go
go/pkg/client/tree.go
go/pkg/client/tree_test.go
go/pkg/command/command.go
go/pkg/uploadinfo/entry.go

Allows virtual inputs to be used with digests. If Contents is provided with InputDigest or the digest does not exist in the CAS, return an error.
Bug: b/324349357, https://github.com/bazelbuild/remote-apis-sdks/issues/525

Extend Virtual Inputs to allow digests

---

go/pkg/tool/tool.go

This is a best effort fix to quote arguments that contains spaces and handle dockerPrivileged platform property which bazel supports.

tool: quote args and handle docker args

---

go/pkg/cas/upload.go

On the Mac, git fsmonitor uses a domain socket in the .git/ folder to keep track of the fsmonitor process. cas chokes on that (see https://crbug.com/40270112).
Therefore, ignore domain sockets.

Ignore domain sockets

---

go.mod
go.sum
go/pkg/client/BUILD.bazel
go/pkg/client/cas_download.go
go/pkg/reader/BUILD.bazel
go/pkg/reader/reader.go
go_deps.bzl

It was initially created due to goroutine leakage as described in https://github.com/klauspost/compress/issues/264, but that has now been fixed in the zstd package. So it's safe to use zstd Encoders/Decoders in sync.Pool directly, as long as concurrency is disabled.

Remove zstdpool-syncpool

---

go/pkg/client/tree.go

Currently we check if we can read the metadata from the file/directory. Even if we can stat the file, it does not necessarily mean we have permissions to open the file/directory. This becomes a problem when we try to open the directory when computing the merkle tree and we don't have read permissions.

Ignore directories without read permissions

---

go/pkg/tool/tool.go

Preserve symlinks in the remotetool to reexecute an action as is, making reproducing actions correct.

Preserve symlinks when using remotetool. This preserves the input tree

---

go/pkg/balancer/BUILD.bazel
go/pkg/balancer/roundrobin.go
go/pkg/cas/client.go
go/pkg/client/capabilities.go
go/pkg/client/client.go
go/pkg/client/client_test.go
go/pkg/fakes/server.go
go/pkg/flags/flags.go
go/pkg/tool/tool.go

This replaces the current load balancer which was copied over from the gcp repo which uses experimental APIs from grpc-go.
Depending on experimental APIs marks the SDK as experimental as well. It also complicates importing the SDK to google3 where everything must be compatbile at head.
This major difference between this simple implementation and the existing one is the maximum number of streams allowed on a single connection.
The existing balancer limits streams to 3 by default and allows configuring that limit.
The new simpler implementation does not enforce any limit.
I have tested the simple balancer by building chromium and android with and without it enabled. I observed no difference in build latency.

add a round robin grpc balancer

---

go/pkg/cas/client.go
go/pkg/client/client.go

The function is useful for creating other gRPC clients that share the same underlying connection. Exporting an interface allows users to reuse the connection pool as well as provide their own pre-dialed connection.

restore NewClientFromConnection

---

go/pkg/command/command.go

Add tool version to ToProto() method, so that this information is captured in the rpl log.

Add tool version to rpl log

---

go/pkg/rexec/rexec.go

Add auxiliary metadata for cache hit actions as well. Previously we only have this for remote execution actions.
Test: run 2 actions with cmake, check the log to see the auxiliary metadata is avaliable for cache hit actions. https://paste.googleplex.com/5312315578908672

Add auxiliary metadata for cache hit actions

---

go/pkg/cas/upload.go

errors.Wrapf used to return nil if the wrapped error is nil. All the modified sites in the previous PR
https://github.com/bazelbuild/remote-apis-sdks/pull/552/files were for non-nil errors except for one, which caused a regression.

fix regression from removing pkg/errors

---

go/cmd/remotetool/BUILD.bazel
go/cmd/remotetool/main.go
go/pkg/tool/BUILD.bazel
go/pkg/tool/embeddedtool.go

In this CL, I'm creating an embeddedtool binary so that I can subsequently use it in reproxytool binary in re-client to implement the log file filtering functionalities. There's no behavior change associated with this CL.
Tested: Ran show_action and show_action_2 (error'ed out) on the new remotetool.

Split the remotetool into a separate library

---

go/pkg/client/exec.go

Reverts bazelbuild/remote-apis-sdks#565
DoNotCache is embedded in the action proto, so if it is set, it also means no cache hit will be received, so implying SkipCache is correct here.

Revert "Change DoNotCache behavior to not imply SkipCache."

---

go/pkg/client/bytestream.go
go/pkg/client/bytestream_test.go
go/pkg/client/cas_test.go
go/pkg/client/retries_test.go

The chunked streaming calls from gRPC do not take a context. The timeout implementation doesn't really timeout because the context is not used. This PR makes it so that the entire gRPC streaming call times out if any individual chunk times out.

fix timeout in stream calls

---

go/pkg/cas/upload.go

Correct #549.
The intention was to skip the file with an unexpected mode, but the “nil, nil” return was actually done in a nested function.
Return ErrSkip to escape the nested function, and correctly return “nil, nil” from visitPath, as was intended.

Ignore unexpected file modes

---

go/pkg/command/command.go
go/pkg/fakes/server.go
go/pkg/rexec/rexec.go
go/pkg/rexec/rexec_test.go

Expose the output file executable bit in the Metadata object.

Expose Output File Executable Bit

---

go/pkg/cas/upload.go

I noticed this bug when trying to update go dependencies.
This may not be a true bug at the current errgroup version we use but it seems like undefined behaviour to use the errgroup ctx after calling Wait()

Fix subtle bug in reusing errgroup context after Wait()

---

go/pkg/credshelper/credshelper.go
go/pkg/credshelper/credshelper_test.go

Removing the requirement for headers to be non-empty since it is possible to authenticate directly through token as well.

Do not enforce headers

---

go/pkg/client/cas_test.go

The call to `binary.Write()` was previously failing because it was being passed a variable length encoded type (int) rather than a fixed length encoding type. This caused the 2000 blobs tests to actually have 0 blobs. Also fix concurrency expectation for the 2000 blobs test.
Tested:
Ran unit tests.

Fix incorrect usage of `binary.Write()` in `TestUpload()`.

---

go/pkg/client/cas_download.go
go/pkg/client/cas_test.go

Method BatchDownloadBlobsWithStats silently ignores decoding error or unsupported codec due to lack of incrementing numErrs.

Report an error on unsupported codec or invalid zstd blob

---

go/README.md
go/pkg/tool/embeddedtool.go
go/pkg/tool/tool.go

This CL update the readme file to show how to re-run an action on another RBE instance.
This CL also fix the flag conflict issue, for execute_action, one and only one of these two flags should be set: [--action_root=PATH|--digest=DIGEST].

Update doc for how to re-run an action with another RBE instance.

---

go/pkg/credshelper/credshelper.go
go/pkg/credshelper/credshelper_test.go

This is not required for every credentials helper, thus doesn't make sense to check for. Each external credshelper can have their own manual authentication checks.

Delete credentials refresh status check

---

go/pkg/balancer/BUILD.bazel
go/pkg/credshelper/BUILD.bazel
go/pkg/credshelper/credshelper.go
go/pkg/credshelper/credshelper_test.go
go/pkg/flags/flags.go

The credentials helper interface now requires that either a token or a headers or both be provided and then creates grpc.credentials.oauth.TokenSource and grpc.credentials.PerRPCCredentials accordingly.

Separate PerRPCCreds from Oauth creds to eliminate undefined behavior

---

go/pkg/contextmd/contextmd.go

This PR modifies the `MergeMetadata` function to create new instances instead of modifying input arguments, preventing unexpected side effects for SDK users.
fixes #606

Prevent side effects in MergeMetadata by creating new instances

---

go/pkg/command/command.go

Explicitly copy the data to prevent unintended changes due to shallow copy occurring based on the characteristics of slices in Golang. This is mentioned in Issue: [610](https://github.com/bazelbuild/remote-apis-sdks/issues/610)

Fix unexpected OutputFiles changes in Command.ToReProto due to shallow copy in Go

---

go/pkg/tool/tool.go
go/pkg/tool/tool_test.go

The --cfg argument can accept these format:
1) '--cfg=key="value"',
2) --cfg='key="value"'
3) --cfg=key=\\"value\\"
but --cfg=key="value" is invalid (no single quote, and also not escaping the double quote).
This CL fix this issue by put the entire --cfg=... string inside of a single quote.

Fix underquoted issues for run_command.sh

---

.github/workflows/golangci-lint.yml
go.mod

This fix will unblock https://github.com/bazelbuild/remote-apis-sdks/pull/616

Enclose Go Version in Workflow File

---

go/pkg/client/bytestream.go

Transient errors are retried by `readStreamedRetried` and it continues reading from how many bytes were already read. When an error happens in the stream call (for example, `DeadlineExceeded`), we were returning that 0 bytes were read.
Since `DeadlineExceeded` is transient, the retry happens and we start from byte 0 again, leading to a lot of duplication.
Note that the other errors return a `fmt.Errorf`, which is not a transient error and won't be retried.
The current behavior seems to be only working to retry at the start of the stream, when no bytes were there yet.

Fix readStreamedRetried retry in bytestream

---

go/pkg/credshelper/credshelper.go
go/pkg/credshelper/credshelper_test.go

It would be nice if we can use the same credential helper with bazel's
https://github.com/EngFlow/credential-helper-spec/blob/main/spec.md
This CL allows credshelper package parses GetCredentialsResponse json message of bazel credential helper.

credshelper accepts bazel credhelper compat GetCredentialsResponse json.
