bazelbuild/remote-apis-sdks

- .bazelci/presubmit.yml
For now just a simple configuration that builds and tests everything on ubuntu1804.
> Add buildkite configuration yaml file.

- go/digest/digest.go
- go/digest/digest_test.go
This is mostly a test for the new copybara setup, I wanted to try a very
small, harmless CL.
> Remove unused function.

- go/client/BUILD.bazel
- go/client/cas_test.go
- go/internal/test/fakes/BUILD.bazel
- go/internal/test/fakes/ac.go
- go/internal/test/fakes/cas.go
- go/internal/test/fakes/exec.go
- go/internal/test/fakes/server.go
If you prefer, I can break it down further and only introduce the fake CAS here, while introducing the fake ActionCache and Exec in a separate CL.
> Adding fakes test package to fake out RBE server.

- go/client/cas.go
- go/client/cas_test.go
- go/internal/test/fakes/ac.go
Also downgrading some log verbosity.
> Adding DownloadActionResult function to intermediate layer.

- go/client/cas.go
- go/client/client.go
Also limiting the default to 50 uploaders. This is the first step in the direction of limiting the overall memory (and network throughput) used by simultaneous uploads.
> Setting CASConcurrency to global accross parallel requests.

- go/pkg/chunker/BUILD.bazel
- go/pkg/chunker/chunker.go
- go/pkg/chunker/chunker_test.go
> A Chunker to support memory-bounded buffered uploads with lazy file

- go/pkg/filemetadata/filemetadata_test.go
> Deflaking file metadata test

- go/pkg/tree/BUILD.bazel
- go/pkg/tree/tree.go
- go/pkg/tree/tree_test.go
also constructing the ActionResult to be updated in the ActionCache. #58
> Transforming the provided local output paths into uploadable Chunkers.

- go/client/cas.go
- go/client/cas_test.go
- go/client/client.go
- go/pkg/fakes/BUILD.bazel
- go/pkg/fakes/cas.go
Fixing #38, #41.
Making sure to not read too much into memory at the same time.
> Implementing batch/parallel downloads

- .bazelci/presubmit.yml
> add "go vet" check to presubmit

- go/client/cas_test.go
- go/client/client.go
- go/client/retries_test.go
- go/cmd/rexec/main.go
- go/flags/flags.go
- go/pkg/fakes/server.go
> Adding an option to specify a separate CAS endpoint.

- go/client/BUILD.bazel
- go/client/cas_test.go
- go/client/client.go
- go/pkg/portpicker/BUILD.bazel
- go/pkg/portpicker/portpicker.go
> Picking an unused port instead of hardcoding it.

- WORKSPACE
> Remove duplicate load line

- go/pkg/client/client.go
- go/pkg/tree/tree.go
There is an internal test use case for this.
> Adding overload with instance name parameter.

- go/pkg/moreflag/moreflag.go
Behavior change: this will allow to parse the flags multiple times, catching new values.
Tested both externally and internally.
> Fixing moreflag to work with both internal and external package.

- go/pkg/client/exec.go
Basically like ExecuteAndWait but with a callback to be able to see the individual updates, so we can get all the nice retryability logic but still know when jobs are queued / executing etc.
> Add ExecuteAndWaitProgress function

- .bazelci/presubmit.yml
This may not be needed if/when this bazelci PR lands:
https://github.com/bazelbuild/continuous-integration/pull/957
> presubmit: shell_commands should exit if any command fails

- go.mod
- go/pkg/balancer/gcp_balancer.go
- remote-apis-sdks-deps.bzl
Following the steps in https://github.com/GoogleCloudPlatform/grpc-gcp-go/commit/9f85758e6b5e238ddd7588d65238224edd72a07b
> Migrate to V2 balancer.

- go/pkg/client/batch_retries_test.go
The test is fine as is -- the problem is that thread sanitizer thinks that every time a single function reads and writes to the same variable it is a data race. In this case, it is not a data race; but it's better to add critical sections than disable tsan for this test entirely (because in other tests this warning might actually be indicative of a problem).
> Fixing thread sanitizer test failure.

- go.mod
- go.sum
Hi,
I'm Ye from the Swarming team. I'd like to make a commit in order to trigger this repo to be mirrored into Chromium's repo (see https://bugs.chromium.org/p/chromium/issues/detail?id=1100806). We need this to be mirrored before we can start using the SDK in the Chromium repo.
Thanks!
Ye
> go: github.com/pkg/errors upgrade => v0.9.1

- go/pkg/client/bytestream.go
- go/pkg/client/cas.go
- go/pkg/client/client.go
In our client, we need to specify more restrict permissions for created directories/files. So let me make file mode created by this sdk configuable.
> make file mode configuable

- go/pkg/client/client.go
This is follow up of https://github.com/bazelbuild/remote-apis-sdks/pull/176
> change default for regular file

- go/pkg/client/cas.go
- go/pkg/client/cas_test.go
We need the list of downloaded files in our client.
> make DownloadDirectory returns outputs

- go/pkg/rexec/rexec.go
- go/pkg/rexec/rexec_test.go
The DownloadOutputs option on the client should also control whether we
download the stdout/stderr streams from the action. Previously
stdout/stderr were downloaded regardless of the DownloadOutputs option.
> DownloadOuputs option includes stdout/stderr streams.

- go/pkg/rexec/rexec.go
This is to be consistent with remote execution clients.
> Log execution-id in addition to command-id in the SDK

- go/pkg/client/cas_test.go
- go/pkg/portpicker/portpicker.go
This is to keep in sync with the internal package.
> Add PortPickerUnusedTB function and use it instead

- go.mod
- go.sum
- go/pkg/chunker/BUILD.bazel
- go/pkg/chunker/chunker.go
- go/pkg/reader/BUILD.bazel
- go/pkg/reader/reader.go
- go/pkg/reader/reader_test.go
- remote-apis-sdks-deps.bzl
This is similar, but replaces #230. It's built on top of #238. I've made it a separate PR in case we don't go with #238, or #238 changes substantially.
> Add compressed file reader.

- go/pkg/chunker/chunker.go
- go/pkg/client/bytestream.go
- go/pkg/client/cas.go
On the midst of PR chains and rebasing, I managed to
leave the functionality off.
> Fix write compression.

- go/pkg/client/cas.go
- go/pkg/client/cas_test.go
- go/pkg/client/client_context.go
- go/pkg/client/retries_test.go
- go/pkg/fakes/cas.go
Also improving the context logging by logging at depth 1 (which prints the caller function line number).
> Fixing a couple of flaky tests.

- go/pkg/client/client.go
Before this patch, BufferSize and TickDuration would only catch if
introduced before UnifiedUploader/Downloader, because the daemon needs
to be restarted once any of these change.
> Bugfix: accidentally introduced order in client options.

- go/pkg/reader/reader.go
The ZSTD lib that we use will launch multiple threads to optimize write
speeds. We were reading from that same buffer without synchronization.
For testing, I ran bazel test with --features=race and --runs_per_test=100.
> Sync read buffer for compressed writes.

- go/pkg/client/client.go
Define DirMode, ExecutableMode, RegularMode options as other client options.
> Define file mode options

- go/pkg/client/tree.go
- go/pkg/filemetadata/BUILD.bazel
- go/pkg/filemetadata/cache.go
This is to utilize cpu for hash calculation when there are many
large files.
Mostly for https://crbug.com/1193375
> calculate filemeta data in parallel

- go/pkg/client/tree.go
- go/pkg/filemetadata/BUILD.bazel
- go/pkg/filemetadata/cache.go
Reverts bazelbuild/remote-apis-sdks#293
The PR didn't improve performance in our prod usage.
ref: https://crbug.com/1193375#c19
Let me revert this for simpler codebase.
> Revert "calculate filemeta data in parallel"

- go/pkg/cas/client.go
- go/pkg/cas/upload.go
Move file IO semaphore from uploader struct to Client, such that
it is shared across all uploaders. Add a comment to uploader to prevent
this in the future.
> [cas] Move file IO semaphore/mutex to Client

- go/pkg/cas/upload.go
Include the filename in the root errors.
> [cas] Improve error messages

- go/pkg/cas/client.go
To match BatchUpdateBlobs.Concurrency.
> [cas] Increase FindMissingBlobs concurrency to 256

- go/pkg/cas/upload.go
- go/pkg/cas/upload_test.go
Use cases:
1) Chrome needs to have different regexp-based path filters in different
UploadItems.
2) reclient needs to ensure that all files are under the exec root
3) reclient needs a non-trivial filter (more than one regexp) per Upload()
call. It doesn't have to be at UploadInput level.
Add UploadInput.Path{Include,Exclude} of type *regexp.Regexp to support
Chrome's use case. Incroporate the regexps into the FS cache key.
Add UploadOptions.Callback that is invoked for each file and may return
ErrSkip if the file should be skipped. This covers both reclient use
cases.
> [cas] Add filtering/callback

- go/pkg/client/cas.go
- go/pkg/client/cas_test.go
This is to investigate https://crbug.com/1208332
> include file path in upload error

- go/pkg/cas/BUILD.bazel
> apply `bazel run //:gazelle`

- .github/workflows/golangci-lint.yml
- .golangci.yml
This updates some default configs for golangci-lint.
https://golangci-lint.run/usage/configuration/#config-file
context: http://b/188387884#comment3
> add .golangci.yml

- go/pkg/chunker/BUILD.bazel
- go/pkg/chunker/chunker.go
- go/pkg/chunker/chunker_test.go
- go/pkg/client/bytestream.go
This is to confirm Reset doesn't return error in
https://crbug.com/1189349#c33
> make (*Chunker).Reset() returns error

- go/pkg/cas/upload.go
A future CL with all PathSpec.Allowlist which is a list of
PathSpec.Path's descendants. It makes more sense for such paths to
be relative to PathSpec.Path than to CWD, but it would be confusing to
have/allow one struct (PathSpec) to contais paths relative to different
dirs.
> [cas] Require PathSpec.Path to be absolute

- .golangci.yml
This is for https://github.com/bazelbuild/remote-apis-sdks/pull/357/files#r647120519
> ignore errors.WithStack

- go/pkg/cas/upload.go
This change is a pure refactoring, in preparation for the commit
that adds support for Allowlist.
> [cas] Refactor code

- go/pkg/cas/upload.go
- go/pkg/cas/upload_test.go
In the Isolate use case, we need to upload a directory partially.
Currently cas package does not let doing it efficiently.
It is possible to upload individual files/directories, but then the
caller has to construct the partial merkle tree themselves. For example,
to upload "/foo" with only "/foo/bar" and "/foo/baz", but not
"/foo/qux", the client has to upload bar and baz, and then calculate the
digest of /foo manually.
It is possible to exclude some paths using UploadOptions.Prelude,
but this filtering is at the UploadOptions level, while we need it at
the PathSpec level. Placing a callback in the PathSpec level makes
caching of intermediate directories difficult. In Go, it is not possible
to tell if two function pointers represent the same function with same
captured input.
Introduce …
> [cas] Add PathSpec.Allowlist

- go/pkg/client/cas.go
This is to know which file we see InvalidArgument error in https://crbug.com/1224224#c5.
> add size check in uploadNonUnified

- go/pkg/cas/upload.go
This is for https://crbug.com/1225524#c14
> cas: fix deadlock

- go/pkg/cas/BUILD.bazel
- go/pkg/cas/upload.go
This is to investigate slowness around https://crbug.com/1225524#c34
> add more logs around upload

- go/pkg/cas/upload.go
This is for performance investigation in https://crbug.com/1193375
> cas: add trace logs

- go/pkg/cas/upload.go
- go/pkg/cas/upload_test.go
This causes deadlock when there are cycles.
This is for https://crbug.com/1237607#c5
> do not follow symlink if it is preserved

- go/pkg/cas/upload.go
This is to debug https://crbug.com/1237607
> cas: elaborate error from os.Lstat in visitSymlink

- go/cmd/remotetool/main.go
- go/pkg/tool/BUILD.bazel
- go/pkg/tool/tool.go
This is for http://b/184322586#comment34
> tool: add UploadBlobV2

- go/pkg/tool/BUILD.bazel
- go/pkg/tool/tool.go
This is for
https://github.com/bazelbuild/remote-apis-sdks/pull/380#pullrequestreview-734706352
> tool: wrap err

- go/pkg/rexec/rexec.go
- go/pkg/rexec/rexec_test.go
Add a function that computes and exposes the output file digests and output directory digests.
> Add GetOutputDigests function

- go/pkg/cas/upload.go
This is speculative fix for https://crbug.com/1288396 and https://crbug.com/1297216.
> replace CloseSend with CloseAndRecv

- go/pkg/client/client.go
- go/pkg/flags/flags.go
Also added an option "use_external_auth_token" that when set to true, would mandate the usae of per RPC creds option starting with the initial Dial to setup the connection
Test: Also implemented the corresponding re-client side of things and ensured that reproxy starts up
> Respect per RPC creds even during Dial()

- go/pkg/client/client.go
> Remove deprecated grpc.WithBalancerName

- go/pkg/filemetadata/filemetadata_test.go
Other tests in this directory depend on these xattr global variables to be set to their defaults. This ensures that the global variables are restored after each test that overwrites them
> Ensure xattr global variables are restored after tests

- .bazelci/presubmit.yml
- WORKSPACE
- go.mod
- go/cmd/remotetool/main.go
- go/cmd/rexec/main.go
- go/pkg/balancer/gcp_balancer.go
- go/pkg/cache/singleflightcache.go
- go/pkg/cas/client.go
- go/pkg/cas/upload.go
- go/pkg/client/exec.go
- go/pkg/portpicker/portpicker.go
- go/pkg/tool/tool.go
Upgrade to go 1.19.5 as it is supported as per https://go.dev/doc/devel/release#policy
> Upgrade to go 1.19.5

- go/pkg/client/bytestream.go
- go/pkg/client/bytestream_test.go
- go/pkg/client/client.go
- Fix lint warnings from the PR #425.
- Remove an unused struct added in the PR #425.
> Fix lint warnings from the PR #425.

- go/pkg/cas/client.go
- go/pkg/cas/upload_test.go
- go/pkg/client/batch_retries_test.go
- go/pkg/client/bytestream_test.go
- go/pkg/client/cas_test.go
- go/pkg/client/client.go
- go/pkg/client/exec.go
- go/pkg/client/retries_test.go
- go/pkg/fakes/cas.go
- go/pkg/fakes/exec.go
- go/pkg/fakes/server.go
Some packages were imported twice under different aliases.
> remove redundant imports

- go/pkg/casng/pubsub.go
The updated implementation favoured concurrency over serial retries. However, it caused a regression because it switched the delivery semantics from at-most-once to at-least-once. That caused errors in how stats are calculated when there is a cache hit.
> revert pubsub to at-most-once

- go/pkg/casng/BUILD.bazel
- go/pkg/casng/batching.go
- go/pkg/casng/batching_write_bytes_test.go
- go/pkg/casng/config.go
- go/pkg/casng/pubsub.go
- go/pkg/casng/streaming_query.go
- go/pkg/casng/uploader.go
- go/pkg/casng/util_test.go
No functional changes.
Added a internal field to trace a request as it propagates throughout the system.
Updated the log message format for easier filtering using grep.
> improve log tracing and filtering

- go/pkg/casng/streaming_upload.go
- go/pkg/casng/upload_digester.go
The stream pipe is used internally to pipe requests from public methods to the shared internal processor, which uses a streaming interface.
The pipe control flow follows its input and output channels. Once the input channel is closed, a control signal is sent to the processor which is forwarded back to the pipe once the processor has processed all requests origniating from that pipe.
Once the pipe receives the termination signal from the processor, it closes its output channel allowing the public method to return (batching) or close its own output channel.
The digestion worker manages file system walks and forwards generated digests to the dispatcher which will be implemented in a subsequent change. The dispatcher would be forwarding the blobs to gRPC workers which would then publish the …
> casng, implement stream pipe and digester worker

- go/pkg/casng/streaming_upload.go
The gRPC batcher handles the batching API of the CAS. It unifies duplicate blobs from multiple requesters into a single request to the remote server, and returns the response to all related requesters.
The unification parameters are configurable and described in the configs.go file as well as in the godocs of public methods.
Dispatching based on byte-size attempts to be as accurate as possible. The bytes are padded by the overhead of serialized proto structures rather than using an arbitrary approximation.
The retry loop is per batch, and only retries failed requests within a batch.
> casng, implemented gRPC batching worker

- go/pkg/casng/batching.go
- go/pkg/casng/upload_digester.go
- go/pkg/casng/util_test.go
Those are easy to miss. Tested internally.
> fix imports for google3 and linter issues

- go/pkg/casng/batching.go
- go/pkg/casng/upload_digester.go
- go/pkg/casng/upload_dispatcher.go
The Exclude field used to reference but now it's a value which meant the
loop variables gets a copy of it and updating it was a noop. This caused
requests to have empty filters which caused cache collisions.
> casng, fix a bug, improve logs and comments

- go/pkg/fakes/exec.go
Adds an implementation for the WaitExecution functionality.
To assert that the expected Operation is passed to it, adds the expected action digest to the operation name (this should be safe; the operation name should be treated as an opaque identifier by clients).
> Implement WaitExecution in the RE API fake

- go/cmd/remotetool/main.go
- go/pkg/tool/tool.go
Feature request from Marc-Antoine's (@maruel).
> remotetool: adding option to upload directory

- go/pkg/credshelper/credshelper.go
- go/pkg/credshelper/credshelper_test.go
- Made externalTokenSource implement PerRPC creds interface as well
- Added headers and tests related to this
>  Update credshelper package

- go/pkg/client/client.go
- go/pkg/credshelper/BUILD.bazel
- go/pkg/credshelper/credshelper.go
- go/pkg/credshelper/credshelper_test.go
- go/pkg/flags/BUILD.bazel
- go/pkg/flags/flags.go
Adding the credentials helper flags and using them in NewClientFromFlags to get tokensource
> Add credshelper flags
